spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/geochat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  redis:
    host: localhost
    port: 6379
    timeout: 6000ms

  mail:
    host: smtp.gmail.com
    port: 587
    username: geo.chat.rut@gmail.com #TODO: Вынести в локальные переменные среды
    password: iyxu hddd lrig xaqh #TODO: Вынести в локальные переменные среды
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  #TODO: Вынести в локальные переменные среды
jwt:
  secret: c3VwZXJfc2VjcmV0X2tleV93aGljaF9pc192ZXJ5X2xvbmc= #TODO: Вынести в локальные переменные среды
  access-token-expiration: 3600000
  refresh-token-expiration: 2592000000
