server:
  port: 8081

spring:
  application:
    name: auth-service

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    repair-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: false

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    timeout: 6000ms

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,metrics,beans,loggers"
  endpoint:
    health:
      show-details: always

# Необходимо для документации. Шаблон для компирования в другие модули
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.geochat.backend: DEBUG
