server:
  port: 8081

spring:
  application:
    name: auth-service

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/geochat}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    repair-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: false

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: 6379
    timeout: 6000ms

  mail:
    host: smtp.gmail.com
    port: 587
    username: geo.chat.rut@gmail.com #TODO: Вынести в локальные переменные среды
    password: iyxu hddd lrig xaqh #TODO: Вынести в локальные переменные среды
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: c3VwZXJfc2VjcmV0X2tleV93aGljaF9pc192ZXJ5X2xvbmc= #TODO: Вынести в локальные переменные среды
  access-token-expiration: 3600000
  refresh-token-expiration: 2592000000

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,metrics,beans,loggers"
  endpoint:
    health:
      show-details: always

# Необходимо для документации. Шаблон для компирования в другие модули
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.geochat.backend: DEBUG
