version: '3.8'

services:
  # PostgreSQL (основная реляционная БД)
  postgres:
    image: postgres:15
    container_name: geochat_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: geochat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geochat_network

  # Redis (для кэширования и хранения сессий)
  redis:
    image: redis:7
    container_name: geochat_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - geochat_network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  # MongoDB (для хранения неструктурированных данных, например, чатов)
  mongo:
    image: mongo:6
    container_name: geochat_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - geochat_network

  # Zookeeper (необходим для Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: geochat_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - geochat_network

  # Kafka (для асинхронных сообщений между сервисами)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: geochat_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - geochat_network

  # Kafka UI (удобный интерфейс для просмотра Kafka)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: geochat_kafka_ui
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8080"
    networks:
      - geochat_network

  # pgAdmin (графический интерфейс для PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: geochat_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: poroshin.info@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - geochat_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  mongo_data:

networks:
  geochat_network:
