services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: geochat_gateway_service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
    networks:
      - geochat_network
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: geochat_auth_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/geochat
      SPRING_REDIS_HOST: redis
      SERVER_PORT: 8081
      SPRING_WEB_CORS_ALLOWED_ORIGINS: "*"
      SPRING_WEB_CORS_ALLOWED_METHODS: "*"
      SPRING_WEB_CORS_ALLOWED_HEADERS: "*"
      SPRING_SECURITY_ALLOWED_ORIGINS: "*"
      SPRING_SECURITY_ALLOWED_METHODS: "*"
      SPRING_SECURITY_ALLOWED_HEADERS: "*"
    networks:
      - geochat_network
    depends_on:
      - postgres
      - redis


networks:
  geochat_network:
    external: true

x-profile: services
