spring:
  application:
    name: GeoChat

  data:
    mongodb:
      uri: mongodb://localhost:27017/geochat

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: geochat-group
      auto-offset-reset: earliest
    producer:
      acks: all
