server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081 #Для запуска сервисов через докер
#          uri: http://localhost:8081 # Для запуска через .jar файлы без обертки в виде докера
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'

jwt:
  secret: ${JWT_SECRET}

webflux:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "Auth Service"
        url: "/auth-service/v3/api-docs"
    group-configs:
      - group: "all-services"
        paths-to-match: "/api/**"
        display-name: "GeoChat API"
    gateway:
      enabled: true
